### ISSUE TITLE
Dockerfile fails to build statsite

### ISSUE THREAD

**Issue by b33rcity** [raintank/graphite-stack#1]
I used docker run to start graphite-stack and received an error about /usr/local/sbin/statsite not being found. I found the line in Dockerfile which sets up statsite to be line 17:

``cd ../statsite; ./bootstrap.sh; ./configure; make; cp src/statsite /usr/local/sbin/; cp sinks/graphite.py /usr/local/sbin/statsite-sink-graphite.py``

I went to the statsite repo and checked the installation instructions, and found they deviate from the Dockerfile command. Changing line 17 to

``cd ../statsite; ./autogen.sh; ./configure; make; cp ./statsite /usr/local/sbin/; cp sinks/graphite.py /usr/local/sbin/statsite-sink-graphite.py``

corrected the problem and I am able to launch the docker container without any errors.

**Comment by Dieterbe** [comment]
thanks @b33rcity ; that seems to work, i'll push the fix soon

**Comment by Dieterbe** [comment]
actually,
you're probably better of using https://hub.docker.com/r/graphiteapp/graphite-statsd/
graphite-stack was created because there was no offical graphite docker image.  But there is now
